# Generated by Django 4.0.4 on 2022-04-25 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_temp', models.FloatField(verbose_name='Shipping Temperature')),
                ('packing', models.CharField(blank=True, max_length=50, null=True)),
                ('appearance', models.CharField(blank=True, max_length=50, null=True)),
                ('service_life', models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Life')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('k', 'kit'), ('r', 'reagent'), ('c', 'consumable')], default='k', max_length=1, verbose_name='Item Type')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Item Name')),
                ('cost', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Unit Cost')),
                ('status', models.CharField(choices=[('n', 'new'), ('d', 'discontinued'), ('a', 'active')], default='n', max_length=1, verbose_name='Item Status')),
                ('quantity', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, verbose_name='Comments')),
                ('manual', models.FileField(blank=True, null=True, upload_to='', verbose_name='User Manual')),
            ],
        ),
        migrations.CreateModel(
            name='MadeReagent',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Item Name')),
                ('comment', models.TextField(blank=True, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Supplier Name')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
