# Generated by Django 4.0.4 on 2022-04-21 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Supplier Name')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('n', 'new'), ('d', 'discontinued'), ('a', 'active')], default='n', max_length=1, verbose_name='Stock Type'),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('k', 'kit'), ('r', 'reagent'), ('c', 'consumable')], default='k', max_length=1, verbose_name='Stock Type'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Stock Name'),
        ),
        migrations.AddField(
            model_name='stock',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockmanufacturer', to='inventory.manufacturer'),
        ),
    ]
