# Generated by Django 4.0.4 on 2022-04-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madereagent',
            name='item',
            field=models.ManyToManyField(through='transactions.Component', to='transactions.purchaseitem'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_manufacturer', to='inventory.manufacturer'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
