# Generated by Django 4.0.4 on 2022-04-25 14:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('billno', models.UUIDField(default=uuid.UUID('65e81a21-967c-4ce3-abc4-792b4b3d8007'), primary_key=True, serialize=False, verbose_name='Bill No.')),
                ('request_date', models.DateTimeField(auto_now=True, verbose_name='Request Date')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='Order Date')),
                ('comment', models.TextField(blank=True, verbose_name='Comments')),
                ('invoice_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='PO Request')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('request_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Supplier Name')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Phone No.')),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gstin', models.CharField(max_length=15, unique=True, verbose_name='GSTIN No.')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('perprice', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Unit Cost')),
                ('received', models.IntegerField(default=0, verbose_name='Received Quantity')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Received Date')),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.purchasebill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasesupplier', to='transactions.supplier'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comments')),
                ('billno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.madereagent')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='transactions.purchaseitem')),
            ],
        ),
    ]
