# Generated by Django 4.0.4 on 2022-04-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='billno',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Bill No.'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(max_length=15, unique=True, verbose_name='GSTIN No.'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Phone No.'),
        ),
    ]
